name: MCP Server Deploy

on:
    push:
      branches:
        - main
    workflow_dispatch:

env:
    AWS_REGION: ap-northeast-1

permissions:
    contents: read
    id-token: write
    actions: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: '20'
            cache: 'npm'
        - uses: aws-actions/setup-sam@v2
        - uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.AWS_REGION }}
        - run: sam build --use-container
        - run: |
            sam deploy \
              --stack-name slack-mcp \
              --region ${{ env.AWS_REGION }} \
              --capabilities CAPABILITY_IAM \
              --no-confirm-changeset \
              --no-fail-on-empty-changeset \
              --force-upload \
              --parameter-overrides \
                ParameterKey=SlackClientId,ParameterValue=xoxb-test-client-id \
                ParameterKey=SlackClientSecret,ParameterValue=test-client-secret-value \
                ParameterKey=SlackSigningSecret,ParameterValue=test-signing-secret-value
